mockserver:
  image: mockserver/mockserver
  ports:
    - '1080:1080'
  environment:
    - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/*.json
    - MOCKSERVER_ENABLE_CORS_FOR_API="true"
    - MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES="true"
  volumes:
    - "./services/:/config"