version: "2.4"
services:
  mockserver:
    image: mockserver/mockserver@sha256:80b3b1a26f3553d0c81a3f3896b5b7274c17b2a2e52f0fd2b28e246bc9efa290
    ports:
      - '1080:1080'
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/*.json
      - MOCKSERVER_ENABLE_CORS_FOR_API="true"
      - MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES="true"
    volumes:
      - "./services/:/config"
