apiVersion: v1
kind: Service
metadata:
  name: {{ include "this.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    prometheus: "true"
    {{- include "this.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appTargetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.monitoringPort }}
      targetPort: {{ .Values.service.monitoringTargetPort }}
      protocol: TCP
      name: monitoring
  selector:
    {{- include "this.selectorLabels" . | nindent 4 }}
